# Generated by Django 4.1.3 on 2022-11-15 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категории вакансий',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_view', to='hh_app.vacancycategory', verbose_name='Категория вакансии'),
            preserve_default=False,
        ),
    ]
