# Generated by Django 4.1.3 on 2022-11-19 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0003_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=300, null=True, verbose_name='Название учебного заведения')),
                ('speciality', models.CharField(max_length=300, null=True, verbose_name='Специальность')),
                ('category_education', models.CharField(choices=[('average', 'Среднее образование'), ('higher', 'Высшее'), ('professional', 'Послевузовское профессиональное образование')], max_length=100, null=True, verbose_name='Категория образования')),
                ('begin_date', models.DateField(max_length=100, null=True, verbose_name='Начало обучения')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='Окончание обучения')),
                ('faculty', models.CharField(max_length=200, null=True, verbose_name='Факультет')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='hh_app.resume', verbose_name='Резюме')),
            ],
        ),
    ]
