# Generated by Django 4.1.3 on 2022-11-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh_app', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=300, null=True, verbose_name='Название органиизации')),
                ('begin_date', models.DateField(max_length=100, null=True, verbose_name='Начало работы')),
                ('end_date', models.DateField(max_length=100, null=True, verbose_name='Окончание работы')),
                ('job_title', models.CharField(max_length=300, null=True, verbose_name='Должность')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='hh_app.resume', verbose_name='Резюме')),
            ],
        ),
    ]
