# Generated by Django 4.1.3 on 2022-11-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hh_app', '0006_alter_education_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('respond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='hh_app.respond', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Сообщение на отклик',
                'verbose_name_plural': 'Сообщения на отклики',
            },
        ),
    ]
